#!/bin/sh
TAG="v1.3-beta"
export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"
echo "\n\nUsing tag: $TAG"

# docker install
sudo apt-get update
sudo apt-get -y -q install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
sudo apt-get update
sudo apt-get -y -q install linux-image-extra-$(uname -r) linux-image-extra-virtual
sudo apt-get -y -q install docker-engine
sudo echo 'DOCKER_OPTS="-D -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"' > /etc/default/docker
sudo service docker restart

# KVM install
# install packages for kvm/qemu
sudo apt-get update;
sudo apt-get install cpu-checker -yq;
sudo apt-get install qemu-system-x86 -yq;
sudo apt-get install qemu-kvm -yq;
sudo apt-get install libvirt-bin -yq;
sudo apt-get install virt-manager -yq;
sudo apt-get install bridge-utils -yq;
sudo apt-get install arpwatch -yq;

# setup rights for tomcat7
sudo sh -c 'echo "tomcat7	ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers';

sudo usermod -aG sudo tomcat7;
sudo usermod -aG kvm tomcat7;
sudo usermod -aG libvirtd tomcat7;
sudo usermod -aG adm tomcat7;
sudo service tomcat7 restart;

wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh;
wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh;
