#!/bin/sh
TAG="v1.2-alpha"
export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"
printf "Using tag: $TAG\n\n"
wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh
printf "### Fix BPS settings for EC2\n\n"
cd ~;
cp ~/wso2bps/repository/conf/carbon.xml ~/wso2bps/repository/conf/carbon.xml.bak
sed -i "s/<\!--HostName>www.wso2.org<\/HostName-->/<HostName>`curl -s http://169.254.169.254/latest/meta-data/public-hostname`<\/HostName>/g" ~/wso2bps/repository/conf/carbon.xml;
wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh;
