#!/bin/sh
TAG="v1.3-beta"
export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/OpenTOSCA.github.io/$TAG"
export BINPATH="https://github.com/OpenTOSCA/OpenTOSCA.github.io/releases/download/$TAG"
echo "\n\nUsing tag: $TAG"
wget -qO- $SCRIPTPATH/includeInstallCommon | sh;

# install packages for kvm/qemu
apt-get update;
apt-get install cpu-checker -yq;
apt-get install qemu-system-x86 -yq;
apt-get install qemu-kvm -yq;
apt-get install libvirt-bin -yq;
apt-get install virt-manager -yq;
apt-get install bridge-utils -yq;
apt-get install arpwatch -yq;

# setup rights for tomcat7
echo 'tomcat7	ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers;

usermod -aG sudo tomcat7;
usermod -aG kvm tomcat7;
usermod -aG libvirtd tomcat7;
usermod -aG adm tomcat7;
service tomcat7 restart;

wget -qO- $SCRIPTPATH/includeInstallCommonStart | sh;
