#!/bin/sh
TAG="master"
export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"
echo "\n\nUsing tag: $TAG"
wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh;
wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh;
