#!/bin/sh
TAG="test"
export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/OpenTOSCA.github.io/$TAG"
export BINPATH="https://github.com/OpenTOSCA/OpenTOSCA.github.io/releases/download/$TAG"
echo "\n\nUsing tag: $TAG"
wget -qO- $SCRIPTPATH/includeInstallCommon | sh;
wget -qO- $SCRIPTPATH/includeInstallCommonStart | sh;