#!/bin/sh
TAG="v1.3-beta"
export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"
printf "Using tag: $TAG\n\n"
wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh;

# install packages for kvm/qemu
sudo apt-get update;
sudo apt-get install cpu-checker -yq;
sudo apt-get install qemu-system-x86 -yq;
sudo apt-get install qemu-kvm -yq;
sudo apt-get install libvirt-bin -yq;
sudo apt-get install virt-manager -yq;
sudo apt-get install bridge-utils -yq;
sudo apt-get install arpwatch -yq;

# setup rights for tomcat7
sudo sh -c 'echo "tomcat7	ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers';

sudo usermod -aG sudo tomcat7;
sudo usermod -aG kvm tomcat7;
sudo usermod -aG libvirtd tomcat7;
sudo usermod -aG adm tomcat7;
sudo service tomcat7 restart;

wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh;
