#!/bin/sh
if [ -z ${CONTAINER_VERSION}${TAG} ]; then
  export CONTAINER_VERSION=master
  export UI_VERSION=master
  export WINERY_VERSION=master

  export TAG="master"
  printf "Using stable version"${TAG}"\n"
  printf "Override by using the environment variable TAG\n"
fi

export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"

wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh
wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh
