#!/bin/sh
if [ -z ${CONTAINER_VERSION}${TAG} ]; then
  export TAG="v2.0.0"
  printf "Using stable version"${TAG}"\n"
  printf "Override by using the environment variable TAG\n"
fi

export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"

wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh
wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh
