#!/bin/sh
export CONTAINER_VERSION=v2.0.0
export UI_VERSION=v2.0.0
export WINERY_VERSION=v2.0.0-M1-OpenTOSCA

export TAG="v2.0.0"
TAG="v2.0.0"
printf "Using stable version"${TAG}"\n"
printf "Override by using the environment variable TAG\n"

export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"
printf "Using tag: $TAG\n\n"
wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh
printf "### Fix BPS settings for EC2\n\n"
cd ~;
cp ~/wso2bps/repository/conf/carbon.xml ~/wso2bps/repository/conf/carbon.xml.bak
sed -i "s/<\!--HostName>www.wso2.org<\/HostName-->/<HostName>`curl -s http://169.254.169.254/latest/meta-data/public-hostname`<\/HostName>/g" ~/wso2bps/repository/conf/carbon.xml;
wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh;
