#!/bin/sh -x

# to fix the hostname unknown problem (Ubuntu > 14.04)
sudo sh -c "echo '127.0.0.1' $(hostname) >> /etc/hosts";

export TAG="v2.0.0"

export CONTAINER_VERSION=v2.0.0
export UI_VERSION=v2.0.0
export WINERY_VERSION=v2.0.0-M1-OpenTOSCA

export SCRIPTPATH="https://raw.githubusercontent.com/OpenTOSCA/install.opentosca.org/$TAG"
printf "Using tag: $TAG\n"
printf "URL: $SCRIPTPATH/includeInstallCommon.sh\n"
echo "DEBUG: x${TAG}x${CONTAINER_VERSION}x${UI_VERSION}x${WINERY_VERSION}x"

wget -qO- $SCRIPTPATH/includeInstallCommon.sh | sh

printf "### Fix BPS settings for OpenStack\n\n"
cd ~
cp ~/wso2bps/repository/conf/carbon.xml ~/wso2bps/repository/conf/carbon.xml.bak
sed -i "s/<\!--HostName>www.wso2.org<\/HostName-->/<HostName>`curl -s http://169.254.169.254/latest/meta-data/public-ipv4`<\/HostName>/g" ~/wso2bps/repository/conf/carbon.xml

wget -qO- $SCRIPTPATH/includeInstallCommonStart.sh | sh
